import { z } from 'zod';
import { artworkSearchResponseSchema } from '../schemas/schemas';
import { BaseTool } from './BaseTool';

const elasticQuerySchema = z.object({
  query: z.record(z.any()).describe(`The Elasticsearch query to execute, generated by the prompt 'elastic_search_query_generator'.`),
  limit: z.number().optional().default(10).describe('The number of resources to return per page.'),
  page: z.number().optional().default(1).describe('The page of results to return. Used for pagination.'),
});

export class ElasticQueryTool extends BaseTool<typeof elasticQuerySchema, any> {
  public readonly name: string = 'elastic-query-tool';
  public readonly description: string = 'Execute an Elasticsearch query against the Art Institute of Chicago collection.'
    + `The query should be in the format of a JSON object and generated by the prompt 'elastic_search_query_generator'.`
    + 'Pagination is supported with the page parameter';

  public readonly inputSchema = elasticQuerySchema;

  constructor() {
    super();
  }

  public async executeCore(input: z.infer<typeof this.inputSchema>) {
    const { query, limit, page } = input;

    const url = new URL(`${this.apiBaseUrl}/artworks/search`);
    url.searchParams.set('page', `${page}`);
    url.searchParams.set('limit', `${limit}`);

    const parsedData = await this.safeApiRequest(
      url,
      {
        method: 'POST',
        body: JSON.stringify(query),
      },
      artworkSearchResponseSchema,
    );
    // Attach pagination info to each artwork for formatting
    parsedData.data.forEach((artwork) => {
      (artwork as any)._pagination = parsedData.pagination;
    });
    return this.formatArtworkList(parsedData.data, 'Elasticsearch query');
  }
}
